name: Deploy to Server

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lowercase Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}/smartsave-ims" >> $GITHUB_ENV

      - name: Create .env file
        run: echo "${{ secrets.PROD_ENV }}" > .env

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Lowercase Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}/smartsave-ims" >> $GITHUB_ENV

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            # Login to GHCR
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Pull the new image
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            
            # Stop and remove the old container if it exists
            if [ "$(docker ps -aq -f name=smartsave-ims)" ]; then
                docker stop smartsave-ims
                docker rm smartsave-ims
            fi
            
            # Run the new container
            docker network create smartsave-net || true
            docker run -d \
              --name smartsave-ims \
              --restart always \
              --network smartsave-net \
              -p 8005:8000 \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
